### PR TITLE
Update Enable Logging Docs

### PR DESCRIPTION
**Pull request by Felixnoo**
Signed-off-by: Felixnoo <felixliu@kubesphere.io>

/assign @wenchajun 
I updated the documents according to our discussion. Please take a look.
If I miss anyone or any SIG group, please invite them as well, thanks.

### CODE REVIEW

**Review by wenchajun — APPROVED** [review]

**Comment by Felixnoo** [comment]
/assign @Patrick-LuoYu 
Please take a look, thanks.

**Pull request merged**
