### PR TITLE
Update Image in S2I Doc

### LINKED ISSUE #1722: Wrong example with creating new service from s2i
As you can see from the following screenshot:

image

Where I circled is a wrong example. Users will get an error tip, see also https://github.com/kubesphere/console/issues/1952

/priority high
/kind bug

### PR DESCRIPTION
**Pull request by Felixnoo**
Signed-off-by: Felixnoo <felixliu@yunify.com>

Fix #1722 .

### CODE REVIEW

**Comment by Felixnoo** [comment]
/assign @LinuxSuRen 
Image updated as discussed in #1722 . [Preview link](https://deploy-preview-1724--kubesphere-v3-1.netlify.app/zh/docs/project-user-guide/image-builder/source-to-image/#步骤-3创建服务).

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Pull request merged**
