### PR TITLE
harbor robot update

### PR DESCRIPTION
**Pull request by rockpanda**
Harbor v2.2以后可以自定义机器人后缀，避免此类问题,就可以直接通过图形化进行harbor集成

### CODE REVIEW

**Comment by rayzhou2017** [comment]
@zheng1 Please check why there is a failing.

**Comment by zheng1** [comment]
@Patrick-LuoYu I don't have permission to rerun this check on netlify, can you help with this?

**Comment by Patrick-LuoYu** [comment]
@zheng1

**Comment by Patrick-LuoYu** [comment]
I also tried the 'Rerun' button and that didn't work either.

image

**Comment by zheng1** [comment]
@Patrick-LuoYu can you rerun in this page https://app.netlify.com/sites/kubesphere-v3-1/deploys/61cd24c5d0818a0007ddb070

**Comment by Patrick-LuoYu** [comment]
I didn't found anything similar to a 'Rerun' button on the page.

image

**Pull request merged**
