### PR TITLE
Add Tutorial Videos in 3.1.x ZH Docs

### PR DESCRIPTION
**Pull request by Felixnoo**
Signed-off-by: Felixnoo <felixliu@kubesphere.io>

/assign @FeynmanZhou 

/cc @kubesphere/sig-docs

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
Do we need to add those videos to the documentation of v3.2.0?

**Comment by Felixnoo** [comment]
> @Felixnoo Do we need to add those videos to the documentation of v3.2.0 as well?

Those videos are for 3.1.x. Some of the UI text shown in those videos would be different from that of 3.2.0. I suggest not putting them in 3.2.0 documentation.

**Pull request merged**
