### PR TITLE
feat: Add jobs user guide

### PR DESCRIPTION
**Pull request by leoendless**
Signed-off-by: leoliu <leoliu@yunify.com>

### CODE REVIEW

**Comment by Sherlock113** [comment]
@leoendless The overall process looks clear to me while please add a part called **Prerequisites** to tell our readers what account they need to use. You can refer to this [guide](https://v2-1.docs.kubesphere.io/docs/quick-start/job-quick-start/). Thanks.

**Comment by Sherlock113** [comment]
@FeynmanZhou Please merge this pr and I will update the wording and format. Thanks.

**Comment by FeynmanZhou** [comment]
@liuboaibc The format looks like a bug on the website, see https://deploy-preview-276--kubesphere-v3.netlify.app/docs/project-user-guide/application-workloads/jobs/

image

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou Please merge this pr and I will update the wording and format. Thanks.

@Sherlock113  Okay, you would better to include [this guide](https://v2-1.docs.kubesphere.io/docs/quick-start/job-quick-start/) in this chapter as the best practice for K8s Job.

**Pull request merged**
