### PR TITLE
add Copied text

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubesphere/website/issues/2442

### CODE REVIEW

**Comment by Arhell** [comment]
https://deploy-preview-2478--kubesphere-v3-1.netlify.app/docs/quick-start/enable-pluggable-components/

**Review by Arhell — COMMENTED** [review]
/assign @yangchuansheng

**Comment by rayzhou2017** [comment]
@harrisonliu5 Please help review this PR.

**Pull request merged**
