### PR TITLE
Update Command for Uninstalling Logging

### PR DESCRIPTION
**Pull request by Felixnoo**
Signed-off-by: Felixnoo <felixliu@kubesphere.io>

[Reference issue](https://github.com/kubesphere/kubesphere/issues/4506).

/cc @wenchajun 
Please review the updates I made, thanks.

### CODE REVIEW

**Comment by wenchajun** [comment]
Maybe we  also should run the following command"
`kubectl edit deployment logsidecar-injector-deploy -n kubesphere-logging-system`

**Comment by Felixnoo** [comment]
> add a command

[Updated](https://github.com/kubesphere/website/pull/2179/commits/1a24e71c733fbf4a5d00125643e0529e790131e8).

**Review by wenchajun — APPROVED** [review]

**Comment by Felixnoo** [comment]
> Maybe we also should run the following command" `kubectl delete deployment logsidecar-injector-deploy -n kubesphere-logging-system`

Thanks. [Updated](https://github.com/kubesphere/website/pull/2179/commits/1a24e71c733fbf4a5d00125643e0529e790131e8).

**Pull request merged**
