### PR TITLE
add new blog of kubectl

### PR DESCRIPTION
**Pull request by faweizhao26**
Signed-off-by: faweizhao26 <faweizhao@kubesphere.io>

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@faweizhao26 @yangchuansheng Is this article original or has it been posted on other websites?

**Comment by redhatxl** [comment]
同意授权发布

**Comment by FeynmanZhou** [comment]
> 同意授权发布

Thanks. I just want to confirm if the article has been already published on the internet. If so, it will affect the website's SEO, we will not accept it. Instead, the original content is welcome.

**Pull request closed without merging**
