### PR TITLE
Add Docs: Customize Cluster Name in Notification Messages

### PR DESCRIPTION
**Pull request by Felixnoo**
Signed-off-by: Felixnoo <felixliu@kubesphere.io>

### CODE REVIEW

**Comment by Felixnoo** [comment]
/assign @wanjunlei 
Hi, please help review this PR. [Preview link](https://deploy-preview-2075--kubesphere-v3-1.netlify.app/docs/cluster-administration/platform-settings/notification-management/customize-cluster-name/).
If I miss anyone or any SIG group, please invite them as well. Thanks.

/assign @VioZhang 
Hi, I added documents per your request. Please take a look, thanks.

**Review by wanjunlei — APPROVED** [review]

**Comment by Felixnoo** [comment]
/hold
Conflicts to be resolved.

**Comment by Felixnoo** [comment]
/assign @Patrick-LuoYu 
Please take a look, thanks.

**Pull request merged**
