### PR TITLE
fix:fixed some mistakes in demos

### PR DESCRIPTION
**Pull request by ruiyaoOps**
Signed-off-by: yaorui <yaorui@yunify.com>

### CODE REVIEW

**Review by rayzhou2017 — CHANGES_REQUESTED** [review]
/cc @ruiyaoOps please resolve the conflicts

**Comment by rayzhou2017** [comment]
You can't remove the conflicts now @ruiyaoOps ?

**Comment by ruiyaoOps** [comment]
I have remove the conflicts, please recheck, thx.

**Pull request closed without merging**
