### PR TITLE
Move MeterSphere Doc to Blogs

### PR DESCRIPTION
**Pull request by Felixnoo**
Signed-off-by: Felixnoo <felixliu@yunify.com>

### CODE REVIEW

**Comment by Felixnoo** [comment]
[Reference blog](https://kubesphere.com.cn/forum/d/3484-kubesphere-devops-metersphere).

**Comment by Felixnoo** [comment]
@FeynmanZhou  
#1639 
Hi, please take a look at this PR when you are available, and sorry for the delay. 
It was Shaowen who configured MeterSphere when I wrote the document. 

Now that the document has to be moved to blogs, I tried to figure out how to configure MeterSphere to add the **Configure Testing on MeterSphere** part to the blog. -> [Preview Link](https://deploy-preview-1734--kubesphere-v3-1.netlify.app/blogs/metersphere-automate-testing/).
However, I still can't configure MeterSphere correctly to make it work well with our DevOps pipeline.
Xnip2021-06-21_18-06-38

So, I need some help, perhaps, from our DevOps team on how to configure MeterSphere...
/cc @kubesphere/sig-devops

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou
> #1639
> Hi, please take a look at this PR when you are available, and sorry for the delay.
> It was Shaowen who configured MeterSphere when I wrote the document.
> 
> Now that the document has to be moved to blogs, I tried to figure out how to configure MeterSphere to add the **Configure Testing on MeterSphere** part to the blog. -> [Preview Link](https://deploy-preview-1734--kubesphere-v3-1.netlify.app/blogs/metersphere-automate-testing/).
> However, I still can't configure MeterSphere correctly to make it work well with our DevOps pipeline.
> Xnip2021-06-21_18-06-38
> 
> So, I need some help, perhaps, from our DevOps team on how to configure MeterSphere...
> /cc @kubesphere/sig-devops

@JohnNiang @LinuxSuRen Could you please help @Felixnoo to take a look at this issue? I can contact the MeterSphere engineers if needed.

**Comment by LinuxSuRen** [comment]
I do not have any experience with MeterSphere. It is necessary to learn MeterSphere from 0 before I try to review this blog. But I'm working on [a new project](https://github.com/LinuxSuRen/ks-devops).

So, it will be great if someone who has experience with MeterSphere can help to review it. For example, engineers from MeterSphere.

**Comment by Felixnoo** [comment]
> > @FeynmanZhou
> > #1639
> > Hi, please take a look at this PR when you are available, and sorry for the delay.
> > It was Shaowen who configured MeterSphere when I wrote the document.
> > Now that the document has to be moved to blogs, I tried to figure out how to configure MeterSphere to add the **Configure Testing on MeterSphere** part to the blog. -> [Preview Link](https://deploy-preview-1734--kubesphere-v3-1.netlify.app/blogs/metersphere-automate-testing/).
> > However, I still can't configure MeterSphere correctly to make it work well with our DevOps pipeline.
> > Xnip2021-06-21_18-06-38
> > So, I need some help, perhaps, from our DevOps team on how to configure MeterSphere...
> > /cc @kubesphere/sig-devops
> 
> @JohnNiang @LinuxSuRen Could you please help @Felixnoo to take a look at this issue? I can contact the MeterSphere engineers if needed.

@FeynmanZhou 
How about we ask for help from Shaowen? He's familiar with MeterSphere and just needs to make some configurations on it. His name will be put in the author anyway...
BTW, I'm starting to think that we'd better make this blog in ZH because the MeterSphere console is not fully localized in EN and its GitHub repo is in ZH.

**Comment by Felixnoo** [comment]
Stale.

**Pull request closed without merging**
