### PR TITLE
Resolves issue #2450 Corrected broken links of porterlb.io 

### PR DESCRIPTION
**Pull request by Santosh1176**
I have corrected many [broken links of Porterlb](https://porterlb.io) to correctly route to [a live working link](https://openelb.github.io/).
This PR resolves issue [#2450](https://github.com/kubesphere/website/issues/2450#issue-1244650285)

Signed-off-by: Santosh - <dtshbl@gmail.com>

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Rebase please

**Comment by Santosh1176** [comment]
> Rebase please

Hi, I am unable to see any conflicts on my local machine. Could you please help me resolve this conflict?

**Comment by Santosh1176** [comment]
Resolved conflict

**Comment by rayzhou2017** [comment]
Thanks @Santosh1176

**Pull request merged**
