### PR TITLE
Update use-an-oauth2-identity-provider.md

### PR DESCRIPTION
**Pull request by daixijun**

### CODE REVIEW

**Comment by Felixnoo** [comment]
Thanks for your contribution!

/cc @RolandMa1986 
Hi, can you help review this PR?

**Comment by Felixnoo** [comment]
/assign @wansir 
Hi, can you help review this PR?

**Comment by FeynmanZhou** [comment]
LGTM.
Hi @wansir @LXM, please help to confirm, thanks.

**Pull request merged**
