### PR TITLE
Update QingCloud Storage setting installation explanation

### PR DESCRIPTION
**Pull request by Sherlock113**
Signed-off-by: Sherlock113 sherlockxu@yunify.com

Added some explanations for how to get access key and ID from QingCloud platform as some users may not know, especially users outside China. Currently the public cloud documentation does not have its English version, so it is better that we added some explanations here.

Besides, the original Chinese doc is outdated. I just copied and pasted the English source file into the ZH-CN folder. If the updated English version looks good to you, you do not need to check the ZH-CN version again as they are the same.

### CODE REVIEW

**Review by min-zh — COMMENTED** [review]
/lgtm

**Review by rayzhou2017 — APPROVED** [review]

**Pull request merged**
