### PR TITLE
Update Commands in 3.2.0 Docs per DevOps SVC Changes

### PR DESCRIPTION
**Pull request by Felixnoo**
Signed-off-by: Felixnoo <felixliu@kubesphere.io>

/assign @kubesphere/sig-devops 
Please take a look, thanks.

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm

Good job!

**Comment by Felixnoo** [comment]
/assign @Patrick-LuoYu 
Please take a look, thanks.

**Review by JohnNiang — CHANGES_REQUESTED** [review]
Everything is ok. But I think we still left `ks-jenkins` somewhere. e.g.:

https://github.com/kubesphere/website/blob/d00442531686f51320ed70bf8a2f968369a5db67/content/en/docs/pluggable-components/uninstall-pluggable-components.md?plain=1#L50

https://github.com/kubesphere/website/blob/d00442531686f51320ed70bf8a2f968369a5db67/content/zh/docs/pluggable-components/uninstall-pluggable-components.md?plain=1#L51

---

https://github.com/kubesphere/website/blob/1838ca679882ae4b98b63144acb195d31b861efc/content/en/docs/devops-user-guide/how-to-use/jenkins-email.md?plain=1#L29

https://github.com/kubesphere/website/blob/1838ca679882ae4b98b63144acb195d31b861efc/content/zh/docs/devops-user-guide/how-to-use/jenkins-email.md?plain=1#L29

**Pull request merged**
