### PR TITLE
add favicons

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubesphere/website/issues/2362

### CODE REVIEW

**Comment by Arhell** [comment]
after add icons
https://realfavicongenerator.net/favicon_checker?protocol=https&site=deploy-preview-2364--kubesphere-v3-1.netlify.app%2F#.YkF1BufP23A

**Comment by FeynmanZhou** [comment]
LGTM.

Hi @weili520 , could you please help to co-review this PR? 
Thanks

**Pull request merged**
