### PR TITLE
add Chinese document for introduction architecture page

### PR DESCRIPTION
**Pull request by Jaycean**
- add Chinese document for introduction architecture page

### CODE REVIEW

**Comment by zryfish** [comment]
There is no ks-apigateway nor ks-account in v3.0, should remove those from the table

**Comment by Jaycean** [comment]
> v3.0中没有ks-apigateway或ks-account，应从表格中删除

Yes, I didn't notice. Thank you

**Comment by rayzhou2017** [comment]
please assign off your pr by  using git commit -a -s

**Comment by Jaycean** [comment]
> please sign off your pr by using git commit -a -s

done

**Review by rayzhou2017 — APPROVED** [review]
/lgtm

**Pull request merged**
