### PR TITLE
docs: add how to deploy chaos mesh on kubesphere

### PR DESCRIPTION
**Pull request by milasuperstar**
Signed-off-by: Mila Wu <wumila1996@gmail.com>

### CODE REVIEW

**Comment by milasuperstar** [comment]
@FeynmanZhou PTAL 👀

**Comment by FeynmanZhou** [comment]
Hi @milasuperstar , thanks for your contribution! As Chaos Mesh is a built-in application of the KubeSphere App Store, I think it might be better to add this guide to [this folder](https://github.com/kubesphere/website/tree/master/content/en/docs/application-store/built-in-apps).

**Comment by milasuperstar** [comment]
> 

done 👀

**Comment by FeynmanZhou** [comment]
Thanks for your contribution!
/approve
/lgtm
cc @kubesphere/sig-docs

**Pull request merged**
