### PR TITLE
Refine Words in Features ZH Doc

### PR DESCRIPTION
**Pull request by Felixnoo**
Signed-off-by: Felixnoo <felixliu@yunify.com>

### CODE REVIEW

**Comment by Felixnoo** [comment]
/assign @FeynmanZhou 
Hi, I updated some ZH words. Please take a look when you are available, thanks. [Preview link](https://deploy-preview-1952--kubesphere-v3-1.netlify.app/zh/docs/introduction/features/).

**Comment by Felixnoo** [comment]
/cc @VioZhang 
FYI.

**Review by VioZhang — APPROVED** [review]

**Pull request merged**
