### PR TITLE
docs-zh: add how to deploy chaos mesh on kubesphere

### PR DESCRIPTION
**Pull request by milasuperstar**
Signed-off-by: Mila Wu <wumila1996@gmail.com>

### CODE REVIEW

**Comment by milasuperstar** [comment]
@FeynmanZhou PTAL ♥️

**Comment by FeynmanZhou** [comment]
Hi @milasuperstar , thanks for your contribution! As Chaos Mesh is a built-in application of the KubeSphere App Store, I think it might be better to add this guide to [this folder](https://github.com/kubesphere/website/tree/master/content/zh/docs/application-store/built-in-apps).

**Comment by milasuperstar** [comment]
> Hi @milasuperstar , thanks for your contribution! As Chaos Mesh is a built-in application of the KubeSphere App Store, I think it might be better to add this guide to [this folder](https://github.com/kubesphere/website/tree/master/content/zh/docs/application-store/built-in-apps).

Done!

**Comment by FeynmanZhou** [comment]
@milasuperstar I just notice that the image URLs are not correct, which caused the broken images on the [documentation](https://kubesphere.io/zh/docs/application-store/built-in-apps/chaos-mesh-app/). Could please help to check and update them accordingly? The URL should be `/images/zh-cn/docs/`.

**Pull request merged**
