### PR TITLE
Add release note items of ks-devops

### PR DESCRIPTION
**Pull request by LinuxSuRen**
/cc @kubesphere/sig-devops 
/area devops

### CODE REVIEW

**Review by JohnNiang — CHANGES_REQUESTED** [review]
I think we have fixed something wrong as below:

- https://github.com/kubesphere/ks-devops/pull/408
- https://github.com/kubesphere/ks-devops/pull/394
- https://github.com/kubesphere/ks-devops/pull/384

**Comment by LinuxSuRen** [comment]
It would be great if you can provide the potential release note items. @JohnNiang

**Comment by JohnNiang** [comment]
@LinuxSuRen , I've updated my comment just now. Please take a look at it.

**Comment by FeynmanZhou** [comment]
> @LinuxSuRen , I've updated my comment just now. Please take a look at it.

Please update it accordingly, the 3.2.1 announcement will be published today. 

Thanks

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Review by JohnNiang — COMMENTED** [review]
Did we ignore the Chinese release notes?

**Comment by FeynmanZhou** [comment]
> Did we ignore the Chinese release notes?

Yes, but I could help you guys to add them to the Chinese documents.

**Pull request merged**
