### PR TITLE
add logging & monitoring faq

### PR DESCRIPTION
**Pull request by huanggze**
Signed-off-by: huanggze <loganhuang@yunify.com>

### CODE REVIEW

**Comment by Sherlock113** [comment]
/lgtm
This faq has minor wording issues, while they won't affect understanding. I will update them after later.
Thank you for writing this section👍

**Review by rayzhou2017 — APPROVED** [review]
/lgtm

**Comment by benjaminhuo** [comment]
@huanggze Thanks for all your efforts, great job! 
We'll miss you :)

**Comment by benjaminhuo** [comment]
@junotx @wanjunlei pls be aware of these changes.

**Pull request merged**
