### PR TITLE
Update upload helm-based app guide

### PR DESCRIPTION
**Pull request by Sherlock113**
Signed-off-by: Sherlock113 <sherlockxu@yunify.com>

### CODE REVIEW

**Comment by rayzhou2017** [comment]
I think it should not be the user `workspace administer`. It should be the tenant with app management access. But for simplicity, we can use workspace administer here.

**Comment by Sherlock113** [comment]
> I think it should not be the user `workspace administer`. It should be the tenant with app management access. But for simplicity, we can use workspace administer here.

This guide is put in the section Workspace Administration. I assume all the guides in the part are designed for workspace administrators. Here, workspace administrators refer to a group of people who refer to this section to see how to administer a workspace instead of a specific user account.

**Comment by Sherlock113** [comment]
Besides, I am actually quite confused here. `project-admin` actually has the permission to upload app templates while the account cannot add an app repository. `ws-admin` can add an app repository. Why should a project-admin user refer to the section Workspace Administration?

**Comment by FeynmanZhou** [comment]
> Besides, I am actually quite confused here. `project-admin` actually has the permission to upload app templates while the account cannot add an app repository. `ws-admin` can add an app repository. Why should a `project-admin` user refer to the section Workspace Administration?

@Sherlock113 @rayzhou2017 

Do you think it will be much clear If we change the chapter title `Workspace Administration` to `Workspace Administration and User Guide`?

**Comment by Sherlock113** [comment]
> > Besides, I am actually quite confused here. `project-admin` actually has the permission to upload app templates while the account cannot add an app repository. `ws-admin` can add an app repository. Why should a `project-admin` user refer to the section Workspace Administration?
> 
> @Sherlock113 @rayzhou2017
> 
> Do you think it will be much clear If we change the chapter title `Workspace Administration` to `Workspace Administration and User Guide`?

This is an option and I am ok with it.

**Comment by rayzhou2017** [comment]
> > > Besides, I am actually quite confused here. `project-admin` actually has the permission to upload app templates while the account cannot add an app repository. `ws-admin` can add an app repository. Why should a `project-admin` user refer to the section Workspace Administration?
> > 
> > 
> > @Sherlock113 @rayzhou2017
> > Do you think it will be much clear If we change the chapter title `Workspace Administration` to `Workspace Administration and User Guide`?
> 
> This is an option and I am ok with it.

I am ok with it

**Review by rayzhou2017 — APPROVED** [review]
/lgtm

**Pull request merged**
