### PR TITLE
Update 3.2.0 Jenkins System Settings Docs

### LINKED ISSUE #2171: Request to adjust the document modifying ConfigMap jenkins-casc-config and reloading it
Since KubeSphere 3.2.0, we've enhanced the configuration and reloading of Jenkins system configuration.

1. For "[Modify the ConfigMap](https://kubesphere.io/docs/devops-user-guide/how-to-use/jenkins-setting/#modify-the-configmap)"

    We need to change config item `jenkins_user.yaml` in ConfigMap `jenkins-casc-config`.

1. For "[Log in to Reload Configuration](https://kubesphere.io/docs/devops-user-guide/how-to-use/jenkins-setting/#log-in-to-jenkins-to-reload-configurations)"

    There is no need to log in to Jenkins dashboard to reload CasC configuration manually. We just need to wait for 70s.

/area devops
/priority high
/cc @kubesphere/sig-devops 
/assign @Felixnoo

### PR DESCRIPTION
**Pull request by Felixnoo**
Signed-off-by: Felixnoo <felixliu@kubesphere.io>

Fix #2171 

/cc @kubesphere/sig-devops 
Please review the updates I made, thanks.

### CODE REVIEW

**Review by JohnNiang — COMMENTED** [review]
Hi @Felixnoo , please focus on this point:

> 2\. For "[Log in to Reload Configuration](https://kubesphere.io/docs/devops-user-guide/how-to-use/jenkins-setting/#log-in-to-jenkins-to-reload-configurations)"
>     There is no need to log in to Jenkins dashboard to reload CasC configuration manually. We just need to wait for 70s.

As a result, I suggest removing the section `Log in to Reload Configuration`. What do you recckon?

**Comment by Felixnoo** [comment]
> Hi @Felixnoo , please focus on the point below:
> 
> > 2. For "[Log in to Reload Configuration](https://kubesphere.io/docs/devops-user-guide/how-to-use/jenkins-setting/#log-in-to-jenkins-to-reload-configurations)"
> > There is no need to log in to Jenkins dashboard to reload CasC configuration manually. We just need to wait for 70s.
> 
> As a result, I suggest removing the section `Log in to Reload Configuration`. What do you reckon?

I understand your concern. However, 2 existing documents in the DevOps chapter have relative links to this part because it has the information about how to log in to the Jenkins dashboard.
I updated the title of this part to `Log in to Jenkins to View Configurations` and made few updates in the following content so that your concern can be addressed and the two existing documents can keep their relative links.

**Comment by Felixnoo** [comment]
> Hi @Felixnoo , please focus on the point below:
> 
> > 2. For "[Log in to Reload Configuration](https://kubesphere.io/docs/devops-user-guide/how-to-use/jenkins-setting/#log-in-to-jenkins-to-reload-configurations)"
> > There is no need to log in to Jenkins dashboard to reload CasC configuration manually. We just need to wait for 70s.
> 
> As a result, I suggest removing the section `Log in to Reload Configuration`. What do you reckon?

@JohnNiang 
Updated.

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
