### PR TITLE
Update application lifecycle management

### PR DESCRIPTION
**Pull request by Sherlock113**
Signed-off-by: Sherlock113 <sherlockxu@yunify.com>

### CODE REVIEW

**Comment by Sherlock113** [comment]
/assign @zheng1 
/cc @FeynmanZhou 

Hi, the wording adjustment of this guide is almost done but I have two questions. Please have a look:

1. I have a question related to the app version. New version number displays in the app store but in fact it is not released yet. Not sure if it is a bug. See this [issue](https://github.com/kubesphere/console/issues/1298).

2. The upgrade part of this guide seems not completed so I tried to add some content. Now I have two app versions: v1.0.0 and v 4.0.2, both released to the app store. For the user who wants to upgrade from v1.0.0, I found a button here:

截屏2020-11-06下午10 49 08

I guess you can click the button to upgrade the app? I clicked it and wait for a while, but it seems the app version remains unchanged. The last updated time is the time I clicked the button **Upgrade** in the image below, but I am not sure whether it is effective or not. Regarding this part, should I write in this guide to tell our readers to just deploy the latest version from the app store directly or tell them to click this button to upgrade?
截屏2020-11-06下午10 50 39

**Comment by Sherlock113** [comment]
Do not merge this pr. It seems that there is sth wrong with the example app in this guide which leads to upgrade failure.

**Comment by zheng1** [comment]
Great works.
/lgtm
/approve

**Comment by Sherlock113** [comment]
@FeynmanZhou Please merge this pr. Thanks.

**Pull request merged**
