### PR TITLE
Integrate Jrog Artifactory in Pipeline

### PR DESCRIPTION
**Pull request by zackzhangkai**

### CODE REVIEW

**Comment by Sherlock113** [comment]
Please solve the conflict first. After that, the pr can be merged. I will update wording later. @zackzhangkai

**Comment by zackzhangkai** [comment]
@Sherlock113 Conflict has been resolved, please review again.

**Comment by FeynmanZhou** [comment]
> @Sherlock113 Conflict has been resolved, please review again.

Please migrate this guide to the `Tool Integration`, it's not suitable to place it under the `introduction`.

https://deploy-preview-387--kubesphere-v3.netlify.app/docs/devops-user-guide/introduction/integrate-jrog-artifactory-in-pipeline/

**Pull request closed without merging**
