### PR TITLE
Update the index of installing ks on linux

### PR DESCRIPTION
**Pull request by rayzhou2017**

### CODE REVIEW

**Comment by Sherlock113** [comment]
/lgtm
BTW: scale up/down is also correct. This is from the OpenShift website:
截屏2020-11-03下午3 27 31

**Comment by rayzhou2017** [comment]
strictly speaking, openshift should be incorrect.

**Comment by Sherlock113** [comment]
Google Doc:
截屏2020-11-04上午8 52 30
截屏2020-11-04上午8 50 47
GigitalOcean Doc:
截屏2020-11-04上午8 48 09
Oracle Doc:
截屏2020-11-04上午8 45 45
Rancher Doc:
截屏2020-11-04上午8 44 54
Azure Doc:
截屏2020-11-04上午8 40 17
AWS Doc:
截屏2020-11-04上午8 39 24
截屏2020-11-04上午8 38 39

Regarding "scale up/down", I am wondering if the docs of these cloud providers are wrong at the same time.

**Comment by rayzhou2017** [comment]
Here is from MS: https://docs.microsoft.com/en-us/azure/data-explorer/manage-cluster-vertical-scaling

**Comment by Sherlock113** [comment]
OK, I see. So the reason for using scale in/out here is that related guides are talking about increasing or decreasing the number of nodes, or horizontal scaling. Scale down/up should be used for vertical scaling. Noted and thanks. 

> Here is from MS: https://docs.microsoft.com/en-us/azure/data-explorer/manage-cluster-vertical-scaling
> https://docs.microsoft.com/en-us/azure/data-explorer/manage-cluster-horizontal-scaling

**Pull request merged**
