### PR TITLE
Update Doc: Integrate SonarQube

### LINKED ISSUE #1597: Deprecated SonarQube token configuration in Jenkins
Relate document is here: <https://kubesphere.io/docs/devops-user-guide/how-to-integrate/sonarqube/#step-6-add-sonarqubeurl-to-the-kubesphere-console>`#Step 05 ##07`.

- Deprecated screenshot

- Current Jenkins configuration
image

/area devops
/kind optimization

### PR DESCRIPTION
**Pull request by Felixnoo**
Signed-off-by: Felixnoo <felixliu@yunify.com>

Fix #1597.

### CODE REVIEW

**Comment by JohnNiang** [comment]
It could be better that put declaration `Fix #1597` in your pr description. If that happens, the issue will close automatically when pr is merged.

By the way, we may miss something about how to create a SonarQube admin token.

**Comment by Felixnoo** [comment]
> It could be better that put declaration `Fix #1597` in your pr description. If that happens, the issue will close automatically when pr is merged.
> 
> By the way, we may miss something about how to create a SonarQube admin token.

Thanks for the info. I added words about how to create a SonarQube admin token.

**Comment by JohnNiang** [comment]
> > It could be better that put declaration `Fix #1597` in your pr description. If that happens, the issue will close automatically when pr is merged.
> > By the way, we may miss something about how to create a SonarQube admin token.
> 
> Thanks for the info. I added words about how to create a SonarQube admin token [in this commit](https://github.com/kubesphere/website/pull/1606/commits/bd2d7af4d9e3e5460f9a9ec1829634aa61713682).

Thanks for your commits. How about the same change for other language?

**Comment by Felixnoo** [comment]
> > > It could be better that put declaration `Fix #1597` in your pr description. If that happens, the issue will close automatically when pr is merged.
> > > By the way, we may miss something about how to create a SonarQube admin token.
> > 
> > 
> > Thanks for the info. I added words about how to create a SonarQube admin token [in this commit](https://github.com/kubesphere/website/pull/1606/commits/bd2d7af4d9e3e5460f9a9ec1829634aa61713682).
> 
> Thanks for your commits. How about the same change for other language?

Sure. Since EN changes are OK to you, I'll make the same in ZH.

**Pull request merged**
