### PR TITLE
Update harbor-app.md

### PR DESCRIPTION
**Pull request by jonahzheng**

### CODE REVIEW

**Review by Felixnoo — COMMENTED** [review]
Hi, thanks for your contribution.

**Comment by FeynmanZhou** [comment]
> /lgtm

@Felixnoo We may need to update the English guide accordingly, right?

**Comment by Felixnoo** [comment]
> > /lgtm
> 
> @Felixnoo We may need to update the English guide accordingly, right?

@FeynmanZhou 
Yes. Already done in #1925

**Pull request merged**
