### PR TITLE
Add log query and web kubectl docs

### PR DESCRIPTION
**Pull request by Ma-Dan**

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@Ma-Dan  Please rebase this PR and merge those 12 commits into 1. There some unnecessary changes and commits were included in this PR.

**Comment by Ma-Dan** [comment]
@FeynmanZhou This PR is rebased and all commits are merged to one.

**Comment by Sherlock113** [comment]
The overall process looks good to me. Please merge this PR if you don't have other issues @FeynmanZhou and I will update the wording accordingly. Thanks.

**Pull request merged**
