### PR TITLE
Update enable DevOps guide

### PR DESCRIPTION
**Pull request by Sherlock113**
Signed-off-by: Sherlock113 <sherlockxu@yunify.com>

### CODE REVIEW

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Review by JohnNiang — COMMENTED** [review]
filename suggestion: `devops.PNG` -> `devops.png`.

**Comment by Sherlock113** [comment]
> filename suggestion: `devops.PNG` -> `devops.png`.

I actually use lower case letters locally while it seems Git did not recognize it and change it back to upper case letters. Em...I will see how to fix it.

**Pull request merged**
