### PR TITLE
Refactor documents under 'account management and permission control'

### LINKED ISSUE #2019: Translate and refactor documents under 'account management and permission control'
Describe：

1.The translation of document directory structure under 'account management and permission control' is incorrect.

2.'Use an LDAP Service' , 'OIDC identity provider' and 'Use an OAuth 2.0 Identity Provider'  need translation.

### PR DESCRIPTION
**Pull request by 123liubao**
Fixes #2019

### CODE REVIEW

**Comment by 123liubao** [comment]
image

I have not updated this document, do I need to modify this problem?

**Comment by Patrick-LuoYu** [comment]
@123liubao Thank you for your contribution!
@weili520 Seems netlify has detected a security problem of our website. Please take a look!

**Comment by weili520** [comment]
> image
> 
> I have not updated this document, do I need to modify this problem?

Thank you very much, It doesn't matter.

**Pull request merged**
