### PR TITLE
update youtube channel link with an alternative nicer link

### LINKED ISSUE #1953: YouTube Channel link could be nicer
Currently the YouTube channel link in the website points to https://www.youtube.com/channel/UCyTdUQUYjf7XLjxECx63Hpw which when looked at doesn't look very great. An alternate link is https://www.youtube.com/c/KubeSphere which looks nicer with the name `KubeSphere` without any random characters

Note: Beware that https://www.youtube.com/channel/KubeSphere link does **NOT** work and gives 404

### PR DESCRIPTION
**Pull request by karuppiah7890**
Fixes #1953 

cc @FeynmanZhou

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@karuppiah7890 Thanks for your contribution!

**Comment by karuppiah7890** [comment]
@FeynmanZhou I have a question, why does the netlify preview site look different? For a moment I thought the new YouTube URL is not picked up by the Hugo config parsers and not showing up in the webpage but the production website has updated link and is all good

**Comment by karuppiah7890** [comment]
I mean the preview link in this comment - https://github.com/kubesphere/website/pull/1954#issuecomment-925074302

**Comment by FeynmanZhou** [comment]
You are right, we just find this problem as well and we never meet this problem in other PRs. We will look into it on Netlify.

**Comment by karuppiah7890** [comment]
Cool 👍

**Pull request merged**
