### PR TITLE
external-apps/deploy-clickhouse: Fix the command bug

### PR DESCRIPTION
**Pull request by molliezhang**
Fix the command bug in  external-apps/deploy-clickhouse.

Please review the updated docs, thanks.

/assign @Sherlock113
/cc @kubesphere/sig-apps

### CODE REVIEW

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Comment by Felixnoo** [comment]
> /cc @Felixnoo Please double check this in the English doc.

The command in EN doc is correct.

**Pull request merged**
